# Conexão com o PostgreSQL (Preparada para a Nuvem e Local)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:PASSWORD}

# Configurações do Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Credenciais do Mercado Pago
mercadopago.access.token=APP_USR-7630723878475342-060420-a06ffcde667bf4da0692fbad18db4894-3446575362